config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'skills'    => 'static_pages#skills'
  get 'classes'   => 'static_pages#classes'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Online Shop - Contact Form",
      :to => "thespislives@gmail.com.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = "We can't send your message right now, please try again soon."
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def skills
  end

  def classes
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Koifrog"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  def icon_link(icon='', link='')
	  link_to ('<i class="'+icon+'"></i>').html_safe, link
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<h3 class="tc"><%= image_tag("logo_color.png", alt:"We will contact you shortly")%></h3>

app/views/contacts/new.html.erb
<div class="mt-0">
  <h3 class="tc mt-1"><%= image_tag("logo_color.png", alt:"Throw us a line", size:"256x256")%></h3>
</div>
<div align="center">
  <div class="row mt-4 tc small-12 large-6">
	<div class="panel">
	  	<%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
	    <%= f.input :name, :required => true, :placeholder=> 'Name' %>
	    <%= f.input :email, :required => true, :placeholder=> 'Email' %>
	    <%= f.input :message, :as => :text, :required => true, :placeholder=> 'Message' %>
	    <div class= "hidden">
	      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
	    </div>
	    <div>
	      </br>
	      <%= f.button :submit, 'Send message', :class=> "button success" %>
	    </div>
	    <% end %>
	</div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="mf-l">
		<div class="row full-width">
			<!-- MAD RESPEKT -->
			<div class="small-12 columns">
                <ul class="small-block-grid-5 large-block-grid-9 footer-links">
					<li>
						<strong>#Respect</strong>
					</li>
					<li>
						<%=
							icon_link('fa fa-linux','http://www.linux.org/')
						%>
					</li>
                    <li>
						<%=
							icon_link('fi-html5','https://www.w3.org/TR/html5/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-css3','https://www.w3.org/TR/CSS/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-foundation','http://foundation.zurb.com/')
						%>
					</li>
	        	</ul>
	    	</div>
			<!-- END MAD RESPEKT -->
		</div>
	</div>
	<div class="mf-d">
		<div class="row full-width">
			<div class="small-12 columns show-for-small-only">
				<span>
					<strong>What we do:</strong>:
				</span>
				<ul class="small-block-grid-8  footer-links">
					<li>
						<%=
							icon_link('fi-social-android','http://developer.android.com/index.html')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-apple','https://developer.apple.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-windows','https://developer.microsoft.com/en-us/windows')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-twitter','https://dev.twitter.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-facebook','https://developers.facebook.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-linkedin','https://developer.linkedin.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-google-plus','https://developers.google.com/+/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-instagram','https://www.instagram.com/developer/')
						%>
					</li>
				</ul>
			</div>
			<div class="small-12 columns hide-for-small">
				<ul class="small-block-grid-9  footer-links">
					<li>
						<strong>What we do:</strong>
					</li>
					<li>
						<%=
							icon_link('fi-social-android','http://developer.android.com/index.html')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-apple','https://developer.apple.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-windows','https://developer.microsoft.com/en-us/windows')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-twitter','https://dev.twitter.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-facebook','https://developers.facebook.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-linkedin','https://developer.linkedin.com/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-google-plus','https://developers.google.com/+/')
						%>
					</li>
					<li>
						<%=
							icon_link('fi-social-instagram','https://www.instagram.com/developer/')
						%>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="mf-xd">
		<div class="row full-width">
			<!-- LETS DO GOOD THINGS -->
	        <div class="small-12 large-6 columns">
				<div style="margin-top:20px;">
					<%= image_tag("logo_grey.png", alt:"Koi fish and frog", size:'160x160')%>
				</div>
	            <span>Let's take our skills and put them to
	                <strong>good</strong>
	                use.</span>
	            <p>
	                Koifrog, an initiative by Aaron McCoy
	            </p>
	        </div>
			<!-- END LETS DO GOOD THINGS -->
			<!-- EDUCATE FTW -->
		    <div class="small-12 large-6 columns">
		        <h4>Learn from us</h4>
				<hr>
		        <ul class="footer-links">
		            <li><%= link_to "Classes", classes_path %></li>
		            <li><%= link_to "Contact", contact_path %></li>
		        </ul>
		    </div>
			<!-- END EDUCATE FTW -->
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div>
        <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
                <li class="name">
                    <h1>
						<%= link_to " #{image_tag('logo_white.png', alt:'Koi fish and frog', size:'32x32')} Koifrog".html_safe, root_path, id: "logo" %>
                    </h1>
                </li>
                <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
                <li class="toggle-topbar menu-icon">
                    <a href="#">
                        <span>Menu</span>
                    </a>
                </li>
            </ul>
            <section class="top-bar-section">
                <!-- Right Nav Section -->
                <ul class="right lighten">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Skills", skills_path %></li>
                    <li><%= link_to "Classes", classes_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                </ul>
            </section>
        </nav>
    </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title><%=full_title(yield(:title))%></title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Alegreya+Sans:400,900|Work+Sans:400,800|Teko:400,700|Archivo+Black|Bevan', :media => "all" %>
        <%= stylesheet_link_tag    "application" %>
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css"/>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
		<%= javascript_include_tag "vendor/modernizr" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
		<%= render 'layouts/messages' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
    </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="row">
    <div class="row">
        <div class="small-12 small-centered columns">
            <h2 class="tc">What is Koifrog?</h2>
            <hr>
            <div class="small-12 small-centered columns">
                <p class="tj">Koifrog's mission is to provide businesses with solutions they need in any way we can. Our key focuses lie in developing resources for your business or otherwise equipping you with the means to develop solutions on your own. We can also act as a
                    transparency layer for your IT department, as a Scrum Master by removing impediments your IT team faces, and as consultants for your development needs. In a nutshell, we apply our technological insights where you need them, and for a fair price.</p>
            </div>
            <h2 class="tc">Why do you need Koifrog?</h2>
            <hr>
            <div class="small-12 medium-6 columns tl">
                <h3>If you're a large business,</h3>
                <p>
                    you need to invest in transparency layers and quality control. Too often we see large businesses whose IT branches that have outgrown not just their administrative staff, but also their business practices in terms of streamlining their production
                    or web presence. This isn't the fault of anyone in particular on your team; as companies change and grow they have to adapt, and we're here to help you with that. Don't suffer from the common symptoms of a quickly growing company! Keep your branding
                    up to today's standards, make sure your web presence is responsive and intuitively navigated, keep your clients and stakeholders happy with the front-end you've provided them, and don't settle for substandard work.</p>
            </div>
            <div class="small-12 medium-6 columns tl">
                <h3>If you're a small business,</h3>
                <p>
                    you need to ditch all of the guesswork when implementing IT solutions, and you need someone with
                    <strong>your</strong>
                    interest in mind when consulting companies about potential solutions. We've seen small warehouses using different software systems to track their inventory, manufacturing, point of sale, shipping and receiving, training, and payroll. Having 6
                    different softwares you need to learn is inherently an obstacle for your business; it means there is very little flexibility in terms of who can accomplish things that need to be done, limited by which softwares people are familiar with. Let us
                    develop a single, custom-tailored app that unifies your work flows in a way that makes hiring new employees easy for them
                    <strong>
                        and
                    </strong>
                    you.</p>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/classes.html.erb
<% provide(:title, "Classes") %>
<h1>StaticPages#classes</h1>
<p>Find me in app/views/static_pages/classes.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
    <div class="small-12 small-centered columns" style="text-align:center;">
        <h2>Welcome to Koifrog</h2>
        <p>Let's talk about how you can do better things on the internet.</p>
    </div>
</div>
<div class="row show-for-medium-up" style="width:100% !important;">
	<hr class="hide-for-small">
	<div class="appendArrows"></div>
    <div class="small-12 columns">
        <div class="stage">
            <div class="bb-d tc">
                <span class="va">
                    <h2 >Web Development</h2>
                    <p>At Koifrog we believe in enabling our clients to do as much or as little as they'd like to.</p>
                    <div class="small-12 medium-6 columns">
                        <h3 class="tc">Put Us to Work</h3>
                        <hr>
                        <p>We can build you a complex web app from scratch to help manage your data, then host it for you on a CDN to deliver your content at screaming fast speeds.</p>
                    </div>
                    <div class="small-12 medium-6 columns">
                        <h3 class="tc">Make Your Own Solution</h3>
                        <hr>
                        <p>We can teach you or your staff to build and manage sites hosted at a location you select. We can host almost anywhere, including your office's server, a third party host provider, or through Koifrog's own hosting plans.</p>
                    </div>
                </span>
            </div>
            <div class="bb-xd tc">
                <div class="va">
                    <h2>Intranet Solutions</h2>
                    <p>If you have resources they need to be centralized.</p>
                    <div class="small-12 medium-6 columns">
                        <h3>Use One App</h3>
                        <hr>
                        <p>We see a lot of businesses using multiple applications for specific tasks; often times businesses will have an ERP, an inventory management software, a point of sale software, and more. Having those software resources communicate to each other is
                            always a hassle, and training employees to use multiple software platforms is inefficient. We can work with you to centralize all of your solutions into a single, custom tailored application.</p>
                    </div>
                    <div class="small-12 medium-6 columns">
                        <h3>Get Training</h3>
                        <hr>
                        <p>We equip administrative staff with enterprise level project collaboration software and training. Never allow your company to be held back by communication bottlenecks. Take decisions you make in the board room directly to the warehouse with Koifrog.</p>
                    </div>
                </div>
            </div>
            <div class="bb-l tc">
                <div class="va">
                    <h2>Consulting and Arbitration</h2>
                    <p>Do you know what your IT Staff are up to?</p>
                    <div class="small-12 medium-6 columns">
                        <h3>Transparency is Key</h3>
                        <hr>
                        <p>How many meetings have you had with your IT crew this month? In those meetings, did you understand the tech talk? Administrative staff shouldn't have to learn the IT world in order to manage their teams, but the unfortunate truth is
                            <strong>if you don't understand what your team is saying there is no way to be sure they are working at all.</strong>
                            Let someone from our team sit in on your meetings as a third party and we'll make sure your team is doing their job. If they hit road blocks or need help, we can step in and give them a hand.</p>
                    </div>
                    <div class="small-12 medium-6 columns">
                        <h3>Do You Need an Expert?</h3>
                        <hr>
                        <p>Koifrog takes a strong stance towards development ethics. We take steps to ensure that our code is not just functional, it is also ethical. If you've run into development problems that need legal or ethical consulting we can provide you with the
                            knowledge you need. We also offer ethical development courses and host an open forum about what is and isn't ethical to practice when developing applications for the web.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row show-for-small-only">
    <div class="small-12 columns">
        <div class="tc">
            <div class="va">
                <div class="small-12 medium-6 columns">
                    <hr>
                    <h3 class="tc">Put Us to Work</h3>
                    <hr>
                    <p>We can build you a web app from scratch to help manage your data, then host it for you on a CDN to deliver your content at screaming fast speeds.</p>
                </div>
                <div class="small-12 medium-6 columns">
                    <hr>
                    <h3 class="tc">Make Your Own Solution</h3>
                    <hr>
                    <p>We can teach you or your staff to build and manage sites hosted at a location you select. We can host almost anywhere, including your office's server, a third party host provider, or through Koifrog's own hosting plans.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
	<hr class="hide-for-small">
	<ul class="small-block-grid-2 medium-block-grid-4 icon-summary tc">
		<li>
			<h3>
				<%=
					icon_link('fi-shopping-cart','https://developer.microsoft.com/en-us/windows')
				%>
			</h3>
			<p>Let's make an online shop you can manage without having to call tech support. Then let's connect it to your inventory so you always know what's in your warehouse.</p>
		</li>
		<li>
			<h3>
				<%=
					icon_link('fi-graph-trend','https://developer.microsoft.com/en-us/windows')
				%>
			</h3>
			<p>Get live data about who is visiting your site; utilizing analytics platforms like Segment.io we can track high resolution data for your site's human interaction.</p>
		</li>
		<li>
			<h3>
				<%=
					icon_link('fi-page-multiple','https://developer.microsoft.com/en-us/windows')
				%>
			</h3>
			<p>Take advantage of our intranet solutions and never go file hunting again. All of your company's resources in one place, all the time, without the clutter or duplicates.</p>
		</li>
		<li>
			<h3>
				<%=
					icon_link('fi-lightbulb','https://developer.microsoft.com/en-us/windows')
				%>
			</h3>
			<p>If you or someone from your organization needs to acquire web development skills, don't waste time trying to learn from generic videos online; let us train your people into a competent web team.</p>
		</li>
	</ul>
</div>

app/views/static_pages/skills.html.erb
<% provide(:title, "Skills") %>
<div class="row" style="max-width:100% !important;">
    <div class="stage small-centered columns">
		
    </div>
</div>